### ISSUE TITLE
Contact Form

### ISSUE THREAD

**Issue by Visham32** [jaylenw/AngularJsTodoApp#28]
**As enhancement:** I would like to add a contact form on this website. After the navigation tabs 'Note List', 'Current List', 'Authentication' and 'GitHub', There will be another navigation tab called 'Contact us'. Therefore when a user will click on it, the latter will be directed in another page where the user will be given a form where he/she will enter the name, email address, country, and the message he/she wants to ask to the owner of the website. When the user will click on submit, the administrator of the website will receive an email showing all the details the user has entered. Below is an example.
![contact](https://cloud.githubusercontent.com/assets/22685311/22207716/9f45ab48-e199-11e6-938a-58c93962f62f.png)

**Comment by jaylenw** [comment]
Currently, I don't want to have a contact form on the web app. If a user would like to contact me or have issues with the app, I hope they would click on the github link that will direct them to this app's repository. If they have a problem with the web app, then they can create an issue here. If they would like to contact me, they can click on my username and email me with my email address that is provided on my Github profile. Also, if someone were to fork this project and launched their own version of this, they would need to change their contact form settings so that I would not receive their visitor's emails, but they will. Thank you @Visham32 for the feedback.
